# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches-ignore: 
      - main   

permissions:
  contents: read
  pages: write 

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -c Release --output ./Release
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Application_Artifact
        path: /home/runner/work/eSimpleBlob/eSimpleBlob/Release/
    - name: Publish
      run: dotnet publish -c Release -o /var/www/sample-app
    - name: Restart the app
      run: |
        export XDG_RUNTIME_DIR=/run/user/$(id -u)
        systemctl --user restart sample-app.service
